---
abstract: 小说站点解析引擎
author:
  - 'Abby Pan <abbypan@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Novel-Robot-Parser
requires:
  Encode::Detect::CJK: v2.0.2
  Encode::Locale: 1.03
  File::Find::Rule: 0.33
  HTML::TableExtract: 2.11
  Moo: 1.000007
  Web::Scraper: 0.37
version: 0.06
