---
abstract: "get novel content from website å°\x8Fè¯´ç«\x99ç\x82¹è§£æ\x9E\x90å¼\x95æ\x93\x8E"
author:
  - 'Abby Pan <abbypan@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Novel-Robot-Parser
requires:
  Encode::Detect::CJK: '0'
  Encode::Locale: '0'
  File::Find::Rule: '0'
  Novel::Robot::Browser: '0'
  URI: '0'
  Web::Scraper: '0'
version: '0.19'
